apiVersion: v2
name: charts/openfga
description: A Kubernetes Helm chart for the OpenFGA project.

type: application
version: 0.2.38
appVersion: "v1.9.0"

home: "https://openfga.github.io/helm-charts"
icon: https://github.com/openfga/community/raw/main/brand-assets/icon/color/openfga-icon-color.svg

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: 8E9B315F6C22E339959DA77B35CCF4BDC9F58F2A
    url: https://openfga.github.io/helm-charts/pgp-public-key.asc

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: oci://ghcr.io/platform-mesh/images/bitnami-charts
    condition: postgresql.enabled
  - name: mysql
    version: "9.6.0"
    repository: oci://ghcr.io/platform-mesh/images/bitnami-charts
    condition: mysql.enabled
  - name: common
    version: "2.13.3"
    repository: oci://ghcr.io/platform-mesh/images/bitnami-charts
    tags:
      - bitnami-common
