name: Build Keycloak Image

concurrency:
  group: keycloak-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      keycloak_image_ref:
        description: "The commit hash of the keycloak image to be build"
        default: "411bc7189c51ca61415abecaf1be8ab13ab24592"
        required: true
      keycloak_image_tag:
        description: "The keycloak tag to be created"
        default: "26.5.2-debian-12-r0"
        required: true
      keycloak_image_context_path:
        description: "The path to the directory holding the dockerfile"
        default: "bitnami/keycloak/26/debian-12"
        required: true

jobs:
  build-image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bitnami/containers
          ref: ${{ github.event.inputs.keycloak_image_ref }}
          fetch-depth: '1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ghcr.io/platform-mesh/upstream-images/keycloak:${{ github.event.inputs.keycloak_image_tag }}
          context: ${{ github.event.inputs.keycloak_image_context_path }}
