name: Build Keycloak Image

concurrency:
  group: keycloak-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      keycloak_image_ref:
        description: "The commit hash of the keycloak image to be build"
        default: "d10816f7ed137e531fd17ec9e40ca6936fd31e0c"
        required: true
      keycloak_image_tag:
        description: "The keycloak tag to be created"
        default: "26.3.2-debian-12-r0"
        required: true
      keycloak_image_context_path:
        description: "The path to the directory holding the dockerfile"
        default: "bitnami/keycloak/26/debian-12"
        required: true

env:
  KEYCLOAK_IMAGE_REF: ${{ github.event.inputs.keycloak_image_ref || 'd10816f7ed137e531fd17ec9e40ca6936fd31e0c' }}
  KEYCLOAK_IMAGE_TAG: ${{ github.event.inputs.keycloak_image_tag || '26.3.2-debian-12-r0' }}
  KEYCLOAK_IMAGE_CONTEXT_PATH: ${{ github.event.inputs.keycloak_image_context_path || 'bitnami/keycloak/26/debian-12' }}


jobs:
  build-image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bitnami/containers
          ref: ${{ env.KEYCLOAK_IMAGE_REF }}
          fetch-depth: '1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ghcr.io/platform-mesh/upstream-images/keycloak:${{ env.KEYCLOAK_IMAGE_TAG }}
          context: ${{ env.KEYCLOAK_IMAGE_CONTEXT_PATH }}
