name: Build postgresql Image

concurrency:
  group: postgresql-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      image_ref:
        description: "The commit hash of the image to be build"
        default: "56273540e12af6a40bdef18bb52ff7c081a0fa5f"
        required: true
      image_tag:
        description: "The tag to be created"
        default: "17.4.0-debian-12-r17"
        required: true
      image_context_path:
        description: "The path to the directory holding the dockerfile"
        default: "bitnami/postgresql/17/debian-12"
        required: true

env:
  IMAGE_REF: ${{ github.event.inputs.image_ref || '56273540e12af6a40bdef18bb52ff7c081a0fa5f' }}
  IMAGE_TAG: ${{ github.event.inputs.image_tag || '17.4.0-debian-12-r17' }}
  IMAGE_CONTEXT_PATH: ${{ github.event.inputs.image_context_path || 'bitnami/postgresql/17/debian-12' }}


jobs:
  build-image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bitnami/containers
          ref: ${{ env.IMAGE_REF }}
          fetch-depth: '1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ghcr.io/platform-mesh/images/postgresql:${{ env.IMAGE_TAG }}
          context: ${{ env.IMAGE_CONTEXT_PATH }}
