name: pipeline-chart
on:
  workflow_call:
    inputs:
      chartRepos:
        required: false
        type: string
        default: ''
      chartFolder:
        required: false
        type: string
        default: 'charts'
      chartName:
        required: true
        type: string
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
      release_branch:
        required: false
        type: string
        default: 'main'
      pushTags:
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.release.outputs.version }}
  push:
    branches:
      - main
      - feat/**

jobs:
  # testChart:
  #   uses: ./.github/workflows/job-test-chart.yml
  #   with:
  #     chartsFolder: ${{ inputs.chartFolder }}
  #     chartName: ${{ inputs.chartName }}
  #     additionalTestFilesCommand: ${{ inputs.additionalTestFilesCommand }}
  #     chartRepos: ${{ inputs.chartRepos }}
  #   secrets: inherit

  # checkHelmDocs:
  #   uses: ./.github/workflows/job-check-helm-chart-docs.yml
  #   with:
  #     chartFolder: ${{ inputs.chartFolder }}/${{ inputs.chartName }}
  #   secrets: inherit

  release:
    # needs: [testChart,checkHelmDocs]
    uses: ./.github/workflows/job-release-chart.yml
    secrets: inherit
    with:
      updateVersion: false
      pushTags: ${{ inputs.pushTags }}
      updateImageTag: false
      chartFolder: ${{ inputs.chartFolder }}/${{ inputs.chartName }}
      release_branch: ${{ inputs.release_branch }}